src/Gym.Uninove.Web/Controllers/EquipmentController.cs
using Gym.Uninove.Core.Entities;
using Gym.Uninove.Core.Interfaces.Repository;
using Gym.Uninove.Web.Models;
using Gym.Uninove.Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Gym.Uninove.Web.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class EquipmentController : Controller
    {

        private readonly IEquipmentRepository _equipmentRepository;

        public EquipmentController(IEquipmentRepository equipmentRepository)
        {
            _equipmentRepository = equipmentRepository;
        }

        public async Task<IActionResult> Index()
        {
            var userSession = HttpContext.Session.GetString("CurrentUser");
            UserSession userCurrent = null;

            // Desserializa a string JSON para um objeto UserSession
            if (!string.IsNullOrEmpty(userSession))
            {
                userCurrent = JsonConvert.DeserializeObject<UserSession>(userSession);
                TempData["Admin"] = userCurrent.Role == "2" ? true : false;
            }

            return View(await this._equipmentRepository.GetAll());
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EquipmentViewModel model)
        {

            if(!ModelState.IsValid) return View(model);

            try
            {

                var equipment = new Equipment
                {
                    Name = model.Name,
                    StatusPurchase = model.StatusPurchase,
                    DatePurchase = model.DatePurchase,
                    UsageTime = DateTime.Now
                };

                await this._equipmentRepository.Add(equipment);
                await this._equipmentRepository.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            var quipment = await this._equipmentRepository.GetById(id);
            return View(quipment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Equipment equipment)
        {

            if(!ModelState.IsValid) return View(equipment);
            if(id != equipment.Id) return View(equipment);

            try
            {
                await this._equipmentRepository.Update(equipment);
                await _equipmentRepository.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var equipment = await this._equipmentRepository.GetById(id);
            if (equipment == null)
            {
                ModelState.AddModelError(string.Empty, "Equipamento não encontrada.");
                return RedirectToAction(nameof(Index));
            }

            return View(equipment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var equipment = await this._equipmentRepository.GetById(id);
                if (equipment == null)
                {
                    ModelState.AddModelError(string.Empty, "Equipamento não encontrada.");
                    return View(equipment);
                }

                await this._equipmentRepository.Delete(equipment.Id);
                await this._equipmentRepository.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Erro ao remover Equipamento. Tente mais tarde.");
                return View();
            }
        }
    }
}

src/Gym.Uninove.Web/Controllers/GymController.cs
using Gym.Uninove.Core.Entities;
using Gym.Uninove.Core.Interfaces.Repository;
using Gym.Uninove.Web.Models;
using Gym.Uninove.Web.Models.ViewModels;
using Gym.Uninove.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using X.PagedList;

namespace Gym.Uninove.Web.Controllers
{
    public class GymController : Controller
    {

        private readonly IGymBranchRepository _gymRepository;
        private readonly IAddressRepository _addressRepository;
        private readonly ImageUploadService _imageUploadService;
        private readonly int PageSize = 9; // Número de itens por página

        public GymController(IGymBranchRepository gymRepository, IAddressRepository addressRepository, ImageUploadService imageUploadService)
        {
            this._gymRepository = gymRepository;
            this._addressRepository = addressRepository;
            this._imageUploadService = imageUploadService;
        }

        public async Task<IActionResult> Index(int? page)
        {

            var userSession = HttpContext.Session.GetString("CurrentUser");
            UserSession userCurrent = null;

            // Desserializa a string JSON para um objeto UserSession
            if (!string.IsNullOrEmpty(userSession))
            {
                userCurrent = JsonConvert.DeserializeObject<UserSession>(userSession);
                TempData["Admin"] = userCurrent.Role == "2" ? true : false;
            }

            return View(await this._gymRepository.GetAllGymWithAddress());

        }


        public ActionResult Details(int id)
        {
            return View();
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GymBranchViewModel gymViewModel)
        {
            if(!ModelState.IsValid) { return View(gymViewModel); }

            try
            {

                var newGym = new GymBranch
                {
                    Name = gymViewModel.GymBranch.Name,
                    UnitNumber = gymViewModel.GymBranch.UnitNumber,
                    Phone = gymViewModel.GymBranch.Phone
                };

                if (!await this.IsGymBranchUniqueAsync(newGym)) 
                {
                    ModelState.AddModelError(string.Empty, "UnitNumber, Phone, or Name must be unique");
                    return View(gymViewModel);
                }

                if (gymViewModel.ImageFile != null && gymViewModel.ImageFile.Length > 0)
                {
                    var uploadFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images/gym");
                    var imagePath = await _imageUploadService.UploadImageAsync(gymViewModel.ImageFile, uploadFolder);
                    gymViewModel.GymBranch.ImagePath = imagePath;

                    newGym.ImagePath = gymViewModel.GymBranch.ImagePath;
                }
                else
                {
                    newGym.ImagePath = "/images/gym/default-gym-image.jpg";
                }

                await this._gymRepository.Add(newGym);
                await this._gymRepository.SaveChangesAsync();

                int gymId = newGym.Id;

                newGym = await this._gymRepository.GetById(gymId);

                var newAddress = new Address
                {
                    Street = gymViewModel.Address.Street,
                    Number = gymViewModel.Address.Number,
                    City = gymViewModel.Address.City,
                    State = gymViewModel.Address.State,
                    Neighborhood = gymViewModel.Address.Neighborhood,
                    Complement = gymViewModel.Address.Complement,
                    ZipCode = gymViewModel.Address.ZipCode,
                    GymId = gymId  // Set the GymId to the Id of the new GymBranch
                };

                newGym.Address = newAddress;

                await this._addressRepository.Add(newAddress);
                await this._addressRepository.SaveChangesAsync();


                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Um erro ocorreu ao adicionar Gym. Tente mais tarde.");
                return View(gymViewModel);
            }
        }


        public async Task<IActionResult> Edit(int id)
        {
            var gym = await this._gymRepository.GetGymWithAddress(id);
            var gymViewModel = new GymBranchViewModel
            {
                Address = gym.Address,
                GymBranch = gym
            };

            return View(gymViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, GymBranchViewModel gym)
        {
            try
            {
                var oldGym = await this._gymRepository.GetGymWithAddress(id);
                if(oldGym == null) return View(gym);

                oldGym.Name = gym.GymBranch.Name;
                oldGym.Phone = gym.GymBranch.Phone;
                oldGym.UnitNumber = gym.GymBranch.UnitNumber;

                oldGym.Address.Street = gym.Address.Street;
                oldGym.Address.Number = gym.Address.Number;
                oldGym.Address.Neighborhood = gym.Address.Neighborhood;
                oldGym.Address.ZipCode = gym.Address.ZipCode;
                oldGym.Address.City = gym.Address.City;
                oldGym.Address.State = gym.Address.State;
                oldGym.Address.Complement = gym.Address.Complement;

                await this._gymRepository.Update(oldGym);
                await this._gymRepository.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Ocorreu um erro ao alterar a academia. Por favor, tente novamente mais tarde.");
                return View(gym);
            }
        }


        public async Task<IActionResult> Delete(int id)
        {
            var gym = await this._gymRepository.GetGymWithAddress(id);
            if (gym == null) 
            {
                ModelState.AddModelError(string.Empty, "Gym não encontrada.");
                return RedirectToAction(nameof(Index));
            }

            return View(gym);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var gym = await this._gymRepository.GetGymWithAddress(id);
                if (gym == null)
                {
                    ModelState.AddModelError(string.Empty, "Gym não encontrada.");
                    return View(gym);
                }

                await this._gymRepository.Delete(id);
                await this._gymRepository.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Erro ao remover Gym. Tente mais tarde.");
                return View();
            }

        }


        // Method Check Properties
        public async Task<bool> IsGymBranchUniqueAsync(GymBranch gymBranch)
        {
            var gyms = await _gymRepository.GetAll();
            return !gyms.Any(g =>
                g.UnitNumber == gymBranch.UnitNumber ||
                g.Phone == gymBranch.Phone ||
                g.Name == gymBranch.Name);
        }

    }
}

src/Gym.Uninove.Web/Controllers/TeacherController.cs
using Gym.Uninove.Core.Entities;
using Gym.Uninove.Core.Interfaces.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Gym.Uninove.Web.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class TeacherController : Controller
    {

        private readonly ITeacherRepository _teacherRepository;

        public TeacherController(ITeacherRepository teacherRepository)
        {
            this._teacherRepository = teacherRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await this._teacherRepository.GetAll());
        }


        public ActionResult Details(int id)
        {
            return View();
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Teacher teacher)
        {
            try
            {
                if (!ModelState.IsValid) return View(teacher);

                await this._teacherRepository.Add(teacher);
                await this._teacherRepository.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Ocorreu um erro ao adicionar Instrutor. Tente mais tarde.");
                return View(teacher);
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            var teacher = await this._teacherRepository.GetById(id);
            return View(teacher);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Teacher newTeacher)
        {
            try
            {
                if (!ModelState.IsValid) return View(newTeacher);
                var oldTeacher = await this._teacherRepository.GetById(id);

                oldTeacher.Name = newTeacher.Name;
                oldTeacher.Description = newTeacher.Description;

                await this._teacherRepository.Update(oldTeacher);
                await this._teacherRepository.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Ocorreu um erro ao alterar Instrutor. Tente mais tarde.");
                return View(newTeacher);
            }
        }


        public async Task<IActionResult> Delete(int id)
        {
            var teacher = await this._teacherRepository.GetById(id);
            if (teacher == null)
            {
                ModelState.AddModelError(string.Empty, "Instrutor não encontrada.");
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, Teacher teacher)
        {
            try
            {
                var oldTeacher = await this._teacherRepository.GetById(id);
                if (teacher.Id != oldTeacher.Id)
                {
                    ModelState.AddModelError(string.Empty, "Instrutor não encontrado.");
                    return View(teacher);
                }

                await this._teacherRepository.Delete(teacher.Id);
                await this._teacherRepository.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Erro ao Remover Instrutor");
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

src/Gym.Uninove.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    var userSession = HttpContextAccessor.HttpContext.Session.GetString("CurrentUser");
    UserSession userCurrent = null;

    // Desserializa a string JSON para um objeto UserSession
    if (!string.IsNullOrEmpty(userSession))
    {
        userCurrent = JsonConvert.DeserializeObject<UserSession>(userSession);
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gym.Uninove.Web</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gym.Uninove.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" 
        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" 
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" 
        integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" 
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/css/bootstrap.min.css" 
        integrity="sha512-rt/SrQ4UNIaGfDyEXZtNcyWvQeOq0QLygHluFQcSjaGB04IxWhal71tKuzP6K8eYXYB6vJV4pHkXcmFGGQ1/0w==" 
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/js/bootstrap.min.js" 
        integrity="sha512-7rusk8kGPFynZWu26OKbTeI+QPoYchtxsmPeBqkHIEXJxeun4yJ4ISYe7C6sz9wdxeE1Gk3VxsIWgCZTc+vX3g==" 
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Uninove Gym</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gym" asp-action="Index">Gyms</a>
                        </li>
                        @if(userCurrent != null)
                        {
                            <li class="nav-item dropdown ml-auto">
                                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img src="caminho-para-sua-foto-de-perfil" class="rounded-circle" width="30" height="30" alt="User">
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-right" aria-labelledby="userDropdown">
                                    @if(userCurrent.Role == "2")
                                    {

                                        <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index"><i class="fa-solid fa-users"></i> Users</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Teacher" asp-action="Index"><i class="fa-solid fa-user-graduate"></i> Instrutores</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Equipment" asp-action="Index"><i class="fa-solid fa-dumbbell"></i> Equipamentos</a>
                                    }
                                    <a class="dropdown-item" href="#"><i class="fa-solid fa-id-badge"></i> Profile</a>
                                    <a class="dropdown-item" asp-controller="User" asp-action="Logout"><i class="fa-solid fa-up-right-from-square"></i> Logout</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item dropdown ml-auto">
                                <a class="nav-link text-dark" asp-area="" asp-action="Authentication" asp-controller="User"><i class="fa-solid fa-circle-user"></i> Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container pb-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted mt-5">
        <!-- Adiciona margem superior -->
        <div class="container">
            &copy; @DateTime.Now.Year - Gym Uninove - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>